name: Deploying to EC2 Instance
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  job1:
      runs-on: ubuntu-latest 
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run remote command via SSH
        uses: D3rHase/ssh-command-action@latest
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
            user: ${{ secrets.USER }}
            private_key: ${{ secrets.PRIVATE_KEY }}
            host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
            command: |
              git -C ~/lms_backend/ pull origin main
  job2:
      runs-on: ubuntu-latest 
      needs: [job1]
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Run remote command via SSH
        uses: D3rHase/ssh-command-action@latest
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
            user: ${{ secrets.USER }}
            private_key: ${{ secrets.PRIVATE_KEY }}
            host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
            command: |
              sudo systemctl restart lms-app
